-- MySQL Script generated by MySQL Workbench
-- Mon Apr 15 17:56:47 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idRoot` INT NOT NULL,
  `Usuario` VARCHAR(45) NOT NULL,
  `Contaseña` VARCHAR(45) NOT NULL,
  `Imagen` VARCHAR(45) NOT NULL,
  `Tipo` INT NULL,
  PRIMARY KEY (`idRoot`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Alumnos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Alumnos` (
  `Matricula` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Edad` INT NOT NULL,
  `Sexo` VARCHAR(45) NOT NULL,
  `Imagen` VARCHAR(45) NOT NULL,
  `Usuario_idRoot` INT NOT NULL,
  PRIMARY KEY (`Matricula`),
  INDEX `fk_Alumnos_Usuario1_idx` (`Usuario_idRoot` ASC) VISIBLE,
  CONSTRAINT `fk_Alumnos_Usuario1`
    FOREIGN KEY (`Usuario_idRoot`)
    REFERENCES `mydb`.`Usuario` (`idRoot`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Visitas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Visitas` (
  `idVisitas` INT NOT NULL,
  `Lugar` VARCHAR(45) NOT NULL,
  `Distancia` VARCHAR(45) NOT NULL,
  `Numero de alumnos` INT NOT NULL,
  `Descipcion` VARCHAR(45) NOT NULL,
  `Alumnos_Matricula` INT NOT NULL,
  PRIMARY KEY (`idVisitas`),
  INDEX `fk_Visitas_Alumnos1_idx` (`Alumnos_Matricula` ASC) VISIBLE,
  CONSTRAINT `fk_Visitas_Alumnos1`
    FOREIGN KEY (`Alumnos_Matricula`)
    REFERENCES `mydb`.`Alumnos` (`Matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Situaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Situaciones` (
  `idSituaciones` INT NOT NULL,
  `Descripcion` VARCHAR(500) NOT NULL,
  `Visitas_idVisitas` INT NOT NULL,
  `Usuario_idRoot` INT NOT NULL,
  PRIMARY KEY (`idSituaciones`),
  INDEX `fk_Situaciones_Visitas1_idx` (`Visitas_idVisitas` ASC) VISIBLE,
  INDEX `fk_Situaciones_Usuario1_idx` (`Usuario_idRoot` ASC) VISIBLE,
  CONSTRAINT `fk_Situaciones_Visitas1`
    FOREIGN KEY (`Visitas_idVisitas`)
    REFERENCES `mydb`.`Visitas` (`idVisitas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Situaciones_Usuario1`
    FOREIGN KEY (`Usuario_idRoot`)
    REFERENCES `mydb`.`Usuario` (`idRoot`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario_has_Visitas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario_has_Visitas` (
  `Usuario_idRoot` INT NOT NULL,
  `Visitas_idVisitas` INT NOT NULL,
  PRIMARY KEY (`Usuario_idRoot`, `Visitas_idVisitas`),
  INDEX `fk_Usuario_has_Visitas_Visitas1_idx` (`Visitas_idVisitas` ASC) VISIBLE,
  INDEX `fk_Usuario_has_Visitas_Usuario1_idx` (`Usuario_idRoot` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_has_Visitas_Usuario1`
    FOREIGN KEY (`Usuario_idRoot`)
    REFERENCES `mydb`.`Usuario` (`idRoot`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_Visitas_Visitas1`
    FOREIGN KEY (`Visitas_idVisitas`)
    REFERENCES `mydb`.`Visitas` (`idVisitas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
